### ISSUE TITLE
Change in Naming Convention

### ISSUE THREAD

**Issue by dorminyk** [the-wozz/network_segments#1]
Determine if a machine is a Laptop or Desktop

Any Laptop should have the "LM" as the first part of the name
Any Desktop will have "DM" as the name...

Followed by Network Location (3 characters?).

i.e.

**LTCHBSERIALNUMBER**
_(LT CHB SERIAL NUMBER)_

let me know if you have any questions

**Comment by the-wozz** [comment]
version ready for testing
